---
- name: установка dhcp
  apt:
    name: isc-dhcp-server
    state: latest
  become: yes
  
- name: установка dhcp
  apt:
    name: isc-dhcp-server-ldap
    state: latest
  become: yes
  
- name: isc-dhcp-server
  template:
    src: isc-dhcp-server.j2
    dest: "/etc/default/isc-dhcp-server"
    owner: root
    group: root
    mode: 0644
  become: yes
  
- name: dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: "/etc/dhcp/dhcpd.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
