---
all:
  children:
    ldap:
      hosts:
        ldap1:
          ansible_host: 192.168.10.1
          ansible_user: user

      vars:
        ansible_ssh_pass: sshpass
        ansible_become_pass: becpass

    dns:
      hosts:
        dns1:
          ansible_host: 192.168.10.1
          ansible_user: user

      vars:
        ansible_ssh_pass: sshpass
        ansible_become_pass: becpass

    dhcp:
      hosts:
        dhcph1:
          ansible_host: 192.168.10.1
          ansible_user: user

      vars:
        ansible_ssh_pass: sshpass
        ansible_become_pass: becpass

    adminstaion:
      hosts:
        adminstation1:
          ansible_host: 192.168.10.1e
          ansible_user: user

      vars:
        ansible_ssh_pass: sshpass
        ansible_become_pass: becpass

